"""create preferences table

Revision ID: 145e80a0a679
Revises: c2eddc2c1f42
Create Date: 2026-08-14 17:47:30.083616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145e80a0a679'
down_revision: Union[str, Sequence[str], None] = 'c2eddc2c1f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investor_type', sa.Enum('HODLER', 'DAY_TRADER', 'NFT_COLLECTOR', name='investortype'), nullable=False),
    sa.Column('assets', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('content_types', sa.ARRAY(sa.Enum('MARKET_NEWS', 'CHARTS', 'SOCIAL', 'FUN', name='contenttype')), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###
