"""create dashboard feedback table

Revision ID: 7cc39d2e5ac8
Revises: ccfd8e68fb7f
Create Date: 2026-08-15 14:29:24.495779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc39d2e5ac8'
down_revision: Union[str, Sequence[str], None] = 'ccfd8e68fb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('content_snapshot', sa.JSON(), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section', 'item_id', name='uq_dashboard_feedback_user_section_item')
    )
    op.create_index(op.f('ix_dashboard_feedback_item_id'), 'dashboard_feedback', ['item_id'], unique=False)
    op.create_index(op.f('ix_dashboard_feedback_section'), 'dashboard_feedback', ['section'], unique=False)
    op.create_index(op.f('ix_dashboard_feedback_user_id'), 'dashboard_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_feedback_user_id'), table_name='dashboard_feedback')
    op.drop_index(op.f('ix_dashboard_feedback_section'), table_name='dashboard_feedback')
    op.drop_index(op.f('ix_dashboard_feedback_item_id'), table_name='dashboard_feedback')
    op.drop_table('dashboard_feedback')
    # ### end Alembic commands ###
